[[section-introduction-and-goals]]
==	Einführung und Ziele
Es gibt viele verschiedene Organe (z.B. Vereine, Clubs, Gruppierungen), welche Aktivitäten  anbieten, an denen Mitglieder teilnehmen können. Es gibt jedoch Situationen, in denen Mitglieder verhindert sind, an einer Aktivität teilzunehmen, z.B. wegen Krankheit, Urlaub oder anderen Verpflichtungen. In solchen Fällen ist es wichtig, dass der Verein über die Abwesenheit eines Mitglieds informiert ist.
Für Jugend und Sport (J+S) Beiträge vom Bund müssen z.B. Anwesenheitslisten pro Aktivität geführt werden. Somit kann belegt werden kann, wann welches Mitglied anwesend war. 

=== Aufgabenstellung
Zur Vereinfachung von Anwesenheitskontrollen soll eine App entwickelt werden. Ein erster Prototyp soll es einem Admin ermöglichen, Training und Mitglieder zu erfassen und auf effiziente Weise, Anwesenheiten von Mitgliedern an einem Training zu tracken.

=== Qualitätsziele
* *Effizienz*
+
Der User soll die Abwesenheiten schneller pflegen können, als mit der bisherigen Lösung.

* *Fehler Minimierung*
+
Die Anzahl falscher Einträge soll minimiert werden.


* *Benutzerfreundlichkeit*
+
Es sollen möglichst viele Benutzer Gefallen an der Anwendung finden. 

=== Stakeholder und Rollen
* *Organverantwortlicher (z.B Chef-Coach)*
+
Der Organverantwortliche möchte Aktivitäten und Mitglieder erfassen und bearbeiten. Weiter möchte er auch Absenzserien erfassen.

* *Aktivitätsverantwortlicher (z.B Coach)*
+
Der Aktivitätsverantwortliche möchte einsehen können, welche Mitglieder an der Aktivität teilnehmen und welche sich abgemeldet haben. Zusätzlich soll er mit einer Anwesenheitsliste erfassen, welche Mitglieder tatsächlich an der Aktivität teilgenommen haben. 

* *Mitglied*
+
Ein Mitglied möchte eine Absenz für eine Aktivität anmelden können.

* *Statistiker (z.B J+S Coach)*
+
Der J+S Coach braucht eine Export, damit die Daten in der J+S Applikation importiert werden können. Die Organe können für Aktivitäten mit Jugendlichen (unter 20 Jahre) Fördergeldern beziehen.


