[[section-introduction-and-goals]]
==	Einführung und Ziele TODO[mwm]
Es gibt viele verschiedene Vereine, Clubs, Grupppieren, usw (Organe) welche verschiedene Aktivitäten (Training, Probe, Ausflug, Wettkampf, Match, Events, Kurse, usw), an denen die Mitglieder teilnehmen können. Es gibt jedoch Situationen, in denen Mitglieder verhindert sind, an einer Aktivität teilzunehmen, z.B. wegen Krankheit, Urlaub oder anderen Verpflichtungen. In solchen Fällen ist es wichtig, dass der Verein über die Abwesenheit eines Mitglieds informiert ist.
Für Jugend und Sport (J&S) Beiträge vom Bund und auch Statistiken müssen Anwesenheitslisten pro Aktivität geführt werden, damit belegt werden kann, wann welches Mitglied anwesend war. 

Ziel der App soll eine vereinfachte Anwesenheitskontrolle sein. Ein erster Prototyp soll es einem Admin ermöglichen, Training und Mitglieder zu erfassen und auf effiziente Weise, Anwesenheiten von Mitgliedern an einem Training zu tracken.


=== Aufgabenstellung

=== Qualitätsziele
* *Titel*
+
Lauftext

=== Stakeholder und Rollen
* *Aktivitätsverantwortlicher (z.B Coach)*
+
Der Aktivitätsverantwortlicher möchte einsehen können welche Mitglieder an der Aktivität teilnehmen und welche sich abgemeldet haben.

* *Mitglied*
+
Ein Mitglied möchte einfach eine Absenz für eine Aktivität melden können.

* *Betreiber (fachlicher oder technischer Schnittstellen Owner)*
+
Betreiber müssen rasch einsehen können, «wie gut» eine Schnittstelle funktioniert. Sprich, ob Aufrufe erfolgreich durchlaufen, ob einzelne Aufrufe oder ein Element innerhalb der Schnittstelle zu Fehlern führt.
+
_Fachliche und technische Applikationsverantwortliche, Betrieb (z.B. auch Cloud)_

