=== Logging

Mit dem Logging-Subsystem wird die Nachvollziehbarkeit und Fehleranalyse von Interfaces ermöglicht. Die Komponente bedient sich dabei etablierten Konzepten aus Logging-Lösungen klassischer Softwareentwicklung, also solchen, welche nicht zur Laufzeit mit Low-Code-Mitteln erweitert werden können. Log-Informationen aus klassischer und Low-Code-Programmierung fließen dabei nahtlos ineinander.

Log-Meldungen werden als Daten geringerer Wichtigkeit erachtet und können zugunsten von Performance oder Speicherplatz verloren gehen bzw. automatisch weggeräumt werden.

Eine Log-Meldung hat ein Log-Level, welches zum einen die Schwere und zum anderen den Detaillierungsgrad der Nachvollziehbarkeit steuert. Die folgende Liste zeigt die Levels, sortiert von _schlimm_ zu _detailliert_:

- *ERROR* schwerwiegendes Ereignis das den Eingriff eines Administrators benötigt.
- *WARN* Ereignis, das die Ausführung aktuell verhindert. Ein alternativer Pfad oder ein Versuch zu späterem Zeitpunkt kann das Problem aber beheben.
- *INFO* relevante Information, welche das korrekte Arbeiten dokumentiert.
- *DEBUG* Ausgabe von Einzelschritten, welche beim Entwickeln oder bei Analyse von Fehlerfällen hilfreich sind.
- *TRACE* sehr detaillierte Informationen mit aktuellen Nutzdaten, die es erlauben, tief in die Programmausführung hereinzuschauen.

==== Datenhaltung